version: "2"
formatters:
  enable:
    - golines
    - gofumpt
    - swaggo
  settings:
    gofumpt:
      module-path: your/module-path
      extra-rules: true
linters:
  default: standard
  enable:
    - revive
    - copyloopvar
    - unconvert
    - nilnesserr
    - intrange
    - ireturn
  settings:
    revive:
      severity: warning
run:
  timeout: 5m
